### ISSUE TITLE
Integration with Grails database migration plugin

### ISSUE THREAD

**Issue by stokito** [tlberglund/groovy-liquibase#44]
The [Grails database migration plugin](http://grails-plugins.github.io/grails-database-migration/docs/manual/guide/single.html) already has support of Groovy DSL for changelogs.
Could you integrate and reuse your code?

**Comment by stevesaliman** [comment]
The goal of the Groovy DSL project is to be a standalone project that simply adds the ability to parse Groovy changelogs for use with Liquibase.  This DSL can then be included by other projects, such as the Gradle Liquibase plugin, or used as a standalone jar with Liquibase itself to add Groovy support to Liquibase.

At first glance, I don't see any good way to integrate the Grails database migration plugin into the DSL code, since it adds a lot of grails specific things that the DSL itself doesn't need.

If anything, it probably makes more sense to have the Grails plugin integrate this DSL to offload the work of handling the ghangelog parsing, freeing the Grails plugin  code to just handle grails related work.

**Comment by stevesaliman** [comment]
I don't see anything else to do in the Groovy DSL for this issue, so I'm closing it.  If there is more work to be done, please open a new issue in the new repository for this project, https://github.com/liquibase/liquibase-groovy-dsl
